---
# OATS is an acceptance testing framework for OpenTelemetry - https://github.com/grafana/oats/tree/main/yaml
version: "3.4"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OTEL_SERVICE_NAME: "dice-server"
      OTEL_SERVICE_VERSION: "0.1.0"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4317
      OTEL_METRIC_EXPORT_INTERVAL: "5000" # so we don't have to wait 60s for metrics
    ports:
      - "8084:8084"
