receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus/collector:
    config:
      scrape_configs:
        - job_name: 'opentelemetry-collector'
          static_configs:
            - targets: ['localhost:8888']

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: http://localhost:9090/api/v1/write
    add_metric_suffixes: true
  otlphttp:
    endpoint: http://localhost:4418
  otlp/logs:
    endpoint: http://localhost:3100/otlp
  logging/metrics:
    verbosity: detailed
  logging/traces:
    verbosity: detailed
  logging/logs:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
      #exporters: [otlphttp,logging/traces]
    metrics:
      receivers: [otlp,prometheus/collector]
      processors: [batch]
      exporters: [prometheusremotewrite]
      #exporters: [prometheusremotewrite,logging/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/logs]
      #exporters: [otlp/logs,logging/logs]
