---
services:
  rolldice:
    image: rolldice-auto
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8083
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-lgtm:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_METRIC_EXPORT_INTERVAL=5000 # so we don't have to wait 60s for metrics
